import { Construction, WBS } from '@/Domain/Entity';

export class ProjectByYearWithWBSAndCS {
    constructor(
        public id: number,
        public no: number,
        public code: string,
        public budget: number,
        public note: string,
        public targetYear: number,
        public budgetDivision: number,
        public largeInvestment: string,
        public mediumInvestment: string,
        public smallInvestment: string,
        public governmentReport: string,
        public wbsLevel1: string,
        public name: string,
        public financialClassification: string,
        public classification: string,
        public segmentCode: string,
        public segmentName: string,
        public lineCode: string,
        public lineName: string,
        public stationCode: string,
        public stationName: string,
        public constructionSectionCode: string,
        public constructionSectionName: string,
        public budgetPurpose: string,
        public wbsLevel2: string | null,
        public inputLevel2: string | null,
        public spareItem1: string | null,
        public spareItem2: string | null,
        public spareItem3: string | null,
        public createdAt: Date,
        public updatedAt: Date,
        public constructions: Construction[] | null,
        public wbs: WBS,
    ) {}
}
