export class ProjectsWithWBS {
    constructor(
        public id: number,
        public no: number,
        public budget: number,
        public note: string,
        public targetYear: number,
        public budgetDivision: number,
        public largeInvestment: string,
        public mediumInvestment: string,
        public smallInvestment: string,
        public governmentReport: string,
        public wbsLevel1: string,
        public name: string,
        public financialClassification: string,
        public classification: string,
        public segmentCode: string,
        public segmentName: string,
        public lineCode: string,
        public lineName: string,
        public stationCode: string,
        public stationName: string,
        public constructionSectionCode: string,
        public constructionSectionName: string,
        public budgetPurpose: string,
        public wbsLevel2: string | null,
        public inputLevel2: string | null,
        public spareItem1: string | null,
        public spareItem2: string | null,
        public spareItem3: string | null,
        public createdAt: Date,
        public updatedAt: Date,
        public wbs: Wbs | null,
    ) {}
}

export class Wbs {
    constructor(
        public accountingCode: string,
        public accountingName: string,
        public assetClassCode: string | null,
        public assetClassName: string | null,
        public april: number | null,
        public may: number | null,
        public june: number | null,
        public july: number | null,
        public august: number | null,
        public september: number | null,
        public october: number | null,
        public november: number | null,
        public december: number | null,
        public january: number | null,
        public february: number | null,
        public march: number | null,
        public annualTotal: number | null,
        public midtermTotal: number,
        public firstYear: number | null,
        public secondYear: number | null,
        public thirdYear: number | null,
        public fourthYear: number | null,
        public createdAt: Date,
        public updatedAt: Date,
    ) {}
}
